library(ggplot2)

library(shinycssloaders)
library(class)

columns <- c("fixed.acidity", "volatile.acidity", "citric.acid", "residual.sugar", "chlorides", "free.sulfur.dioxide","total.sulfur.dioxide", "density","pH", "sulphates", "alcohol" )

shinyUI(navbarPage("Project 3 - Min He",
                   tabPanel("Projects requirements",
                            mainPanel(
                              HTML("
<h2 style='color:#009933'>Requirements from Project 3</h2>
     
<h3>Creating a Shiny App</h3>
<p>The goal of this project is to create a nice looking shiny app that can be used to explore data and model it.</p>
<h3>Project Work</h3>
<p>
All project work should be done in a github repo. Ideally, you have connected RStudio with github and can work from the command line within RStudio. All major updates should be made through github so we can track your activity.</p>
<p>
We will run your app from gitHub using RStudio so make sure it is set up correctly to do that (see lecture for reference to setting it up, try it yourself to make sure it works!).</p>
<p>You should simply post your github repo URL as your submission.</p>
</p>
<h3>Find a data set you are interested in</h3>
<p>For this project I'm going to let you choose your own data set. This should be a data set that has at least two categorical and at least two quantitive variables. See the previous project for a list of places with datasets. Alternatively, you could pull data from the web within your app (for instance baseball data (<a href=https://pitchrx.cpsievert.me/>link</a>) or twitter data (<a href=https://cran.r-project.org/web/packages/rtweet/vignettes/intro.html>link</a>)). Choose something you are interested in and have ideas for investigating!</p>
<h3>App Requirements</h3>
<ul>
    <li>Your app should have multiple pages (tabs) to it. I don’t care if you use the built in tabs for shiny or a package like shinydashboard - use the method you prefer.
      <ul>
        <li>An information page that describes the data and abilities of the app</li>
        <b style='color:#0000FF'>Please refer to the tab 'Introduction to Data'</b>
        <li>A data exploration page where common numeric and graphical summaries can be created by the user</li>
        <b style='color:#0000FF'>Please refer to the tab 'Exploration of the wine data', User can draw the box plot for all the wine, or just red wine/white wine. If the user to choose draw box plot for all wines, the user can set color for different wine type (one UI dynamics)</b>
        <li>A page with either clustering (include a dendogram) or principal components analysis (include a biplot) - again where the user can specify aspects of the algorithm</li>
        <b style='color:#0000FF'>Please refer to the . Principal components analysis was included, and the biplot was included as well. The user can pick which predictors are included for the PCA. A scree plot for the eigenvalues of factors or principal components in an analysis was also included.</b>
        <li>A page for modeling - see below for details</li>
        <li>A page that allows the user to scroll through the data (or subset of data of interest)</li>
        <b style='color:#0000FF'>Please refer to the 'Analysis with unsupervised learning' tab. Principal components analysis was included, and the biplot was included as well. The user can pick which predictors are included for the PCA. A scree plot for the eigenvalues of factors or principal components in an analysis was also included.</b>
      </ul>
    </li>
    <li> You should have at least two different dynamic UI elements.</li>
    <b style='color:#0000FF'>1. The user can set color for different wine type (one UI dynamics) based on the data the user wants to draw. 
    <br>2. The results for the model was generated by using the uiOutput.
    <br>3. The predicted result based on the user's input is updated after user click the predict button.
    </b>
    <li> You should have a button that allows the user to save a plot they are viewing to a file.</li>
    <b style='color:#0000FF'>In the data exploratory page, the user can save the box plot for what they plot.</b>
    <li> You should have an option to allow the user to save the data currently being used for a plot (or when they are looking at the data table) to a .csv (or other) file.</li>
    <b style='color:#0000FF'>In the data exploratory page, the user can save data they are using to draw the boxplot.</b>
    <li> You should utilize the ability to click on a plot or select a region in some way.</li>
    <b style='color:#0000FF'>In the data exploratory page, the user can click the points and brush the area and the data within will be displayed in a table.</b>
    <li> You should include some type of math type (maybe an equation or just a special symbol you need to use mathJax for).</li>
    <b style='color:#0000FF'>1. The formulas for the PCA method were displayed.
    <br> 2. The formula for the ridge regression is also included.
    </b>
    <li> You should include a link to something and some other formatted text.</li>
    <b style='color:#0000FF'>The links to the source data and other references were included.</b>
    <li> Modeling
    <ul>
      <li>(At least) two supervised learning models (feel free to branch out to things we didn’t discuss if you’d like)</li>
      <b style='color:#0000FF'>The multinomial and knn supervision methods were included, and in those 2 methods, the quality response variable is treated as a categorical variable, and the ridge regression method was also included, the quality response variable was treated as numeric variable.</b>
      <li> You should give the user some functionality for choosing model settings (variables used, number of trees, etc.) and for changing relevant output</li>
      <b style='color:#0000FF'>The user can choose the predictors, and in the model, cross validation was used for the ridge regression to choose the best lamda, and the user can also choose how many records used for training.</b>
      <li> You should give the user a way to use the model for prediction (they should be able to select the values of the predictors)</li>
      <b style='color:#0000FF'>After the training/testing split was done with the training percentage defined by the user, the model will be trained and used to predict the testing data's response quality, and the user can input the values for predictors, and get the response value based on the trained model.</b>
    </ul>
    </li>
</ul>

"))),
                   
                   tabPanel("Introduction to Data",
                            mainPanel(
                              HTML("
<h3>Data Set Information:(copy from <a href='https://archive.ics.uci.edu/ml/datasets/wine+quality'>https://archive.ics.uci.edu</a>)</h3>
<p>Keywords: repeated measures, ordinal regression</p>
<hr><h3>Description</h3>
<p>The two datasets are related to red and white variants of the Portuguese 'Vinho Verde' wine. For more details, consult: [Web Link] or the reference [Cortez et al., 2009]. Due to privacy and logistic issues, only physicochemical (inputs) and sensory (the output) variables are available (e.g. there is no data about grape types, wine brand, wine selling price, etc.).</p>
<p>EThese datasets can be viewed as classification or regression tasks. The classes are ordered and not balanced (e.g. there are many more normal wines than excellent or poor ones). Outlier detection algorithms could be used to detect the few excellent or poor wines. Also, we are not sure if all input variables are relevant. So it could be interesting to test feature selection methods.</p>
<hr>
<h3>Attribute Information:</h3>
Input variables (based on physicochemical tests):
1 - fixed acidity<hr>
2 - volatile acidity<hr>
3 - citric acid<hr>
4 - residual sugar<hr>
5 - chlorides<hr>
6 - free sulfur dioxide<hr>
7 - total sulfur dioxide<hr>
8 - density<hr>
9 - pH<hr>
10 - sulphates<hr>
11 - alcohol<hr>
Output variable (based on sensory data):<hr>
12 - quality (score between 0 and 10)<hr>
<h3>The abilities of the App</h3>
<h4>Data Exploratory</h4>
<h4>Allow user to pick up the model and select the predictors</h4>
<h4>Allow user get the reponse result based on user's inputs for the predictors</h4>
<p>
</p>
")
                            )),
                   # Application title
                   tabPanel("Exploration of the wine data",
                            # Sidebar with options for the data set
                            sidebarLayout(
                              sidebarPanel(
                                h3("Select the wine type:"),
                                selectizeInput("wine_type", "wine type", selected = "all", choices = c('all','red','white')),
                                br(),
                                checkboxInput("hideplot", "Hide the plot"),
                                # selectInput("scatterplot_y", "Y column for the boxplot", columns),
                                # sliderInput("size", "Size of Points on Graph", min = 1, max = 10, value = 3, step = 1),
                                conditionalPanel(condition = "input.wine_type == 'all'",
                                                 checkboxInput("cb_wine_type", h5("Color Code based on wine type (only shows when all is selected)", style = "color:red;"))
                                )
                              ),
                              
                              # Show output
                              mainPanel(
                                helpText(a("Click Here to see my datasource",href="https://archive.ics.uci.edu/ml/datasets/wine+quality")
                                ),
                                conditionalPanel(condition = "input.hideplot == false",
                                                 downloadButton('downloadPlot', 'Download Plot'),
                                                 
                                                 withSpinner(plotOutput("wine_dataPlot", height = 300,
                                                            # Equivalent to: click = clickOpts(id = "plot_click")
                                                            click = "plot_click",
                                                            brush = brushOpts(id = "plot1_brush")
                                                 ))
                                                 ),
                                
                                fluidPage(
                                  fluidRow(
                                    column(width = 8,
                                           h4("Points near click"),
                                           DT::dataTableOutput("plot_clicked_points")
                                    ),
                                    column(width = 8,
                                           h4("Brushed points"),
                                           DT::dataTableOutput("brush_info")
                                    )
                                  )
                                ),
                                downloadButton("downloadData", "Download"),
                                DT::dataTableOutput("table")
                              )
                            )
                   ),
                   
                   # Using KNN to analyze the data
                   tabPanel("Analysis with supervised methods",
                            # Sidebar with options for the data set
                            sidebarLayout(
                              sidebarPanel(
                                h3("Select the supervised learning method:"),
                                selectizeInput("SupervisedMethod", "SupervisedMethod", selected = "knn (quality as factor)", choices = c('knn (quality as factor)','multinomial (quality as factor)', 'Ridge regression (quality as numeric)')),
                                
                                h3("Model formula for the ridge model:"),
                                withMathJax(helpText("$$ \\widehat{\\beta}^{ridge}=\\arg\\min_{\\beta\\in R}{||{y-XB}||_2^2}+ \\lambda ||B||_2^2$$")),
                                h3("Training data percentage:"),
                                sliderInput("TrainingPercent", "Percent of data used for training", min = 30, max = 100, value = 80, step = 1),
                                sliderInput("NeighborCount", "Number of neighbors used for KNN", min = 1, max = 20, value = 10, step = 1),
                                selectInput("SelectedColumns", "Select Predictors (for KNN and multinomial)", choices =columns,multiple = TRUE,selected = columns),
                                
                                h5("Predict the response quality based on the following inputs (as I have already stardarized the data, the range will be 0, 1 (with default of 0.5):"),
                                
                                # User's input for the predictors.
                                numericInput(inputId='fixed.acidity', label='fixed.acidity', value = 0.5),
                                numericInput(inputId='volatile.acidity', label='volatile.acidity', value = 0.5),
                                numericInput(inputId='citric.acid', label='citric.acid', value = 0.5),
                                numericInput(inputId='residual.sugar', label='residual.sugar', value = 0.5),
                                numericInput(inputId='chlorides', label='chlorides', value = 0.5),
                                numericInput(inputId='free.sulfur.dioxide', label='free.sulfur.dioxide', value = 0.5),
                                numericInput(inputId='total.sulfur.dioxide', label='total.sulfur.dioxide', value = 0.5),
                                numericInput(inputId='density', label='density', value = 0.5),
                                numericInput(inputId='pH', label='pH', value = 0.5),
                                numericInput(inputId='sulphates', label='sulphates', value = 0.5),
                                numericInput(inputId='alcohol', label='alcohol', value = 0.5),
                                uiOutput("predicted_quality"),
                                actionButton("predict_click","Generate the predicted quality")
                              ),
                              
                              # Show output
                              mainPanel(
                                helpText("When the quality was treated as a categorical variable, the confusion matrix will be provided."),
                                withSpinner(uiOutput("knn_output")) ,
                                uiOutput("misclassifiedPct")
                              )
                            )
                   ),
                   
                   # Using PCA to analyze the data
                   tabPanel("Analysis with unsupervised learning",
                            # Sidebar with options for the data set
                            sidebarLayout(
                              sidebarPanel(
                                selectInput("PcaSelectedColumns","Select Predictors", choices =columns,multiple = TRUE,selected = columns),
                                
                                helpText("Based on the WIKI page for PCA, in order to maximize variance, the first weight vector  thus has to satisfy"),
                                withMathJax(helpText("$$\\ w_{(1)}=\\arg\\max_{||{w}||=1}\\{\\sum_i{(t_i)_{(i)}^2}\\}=\\arg\\max_{||{w}||=1}\\{\\sum_i{(x_{(i)}*w)^2}\\}$$")),
                                withMathJax(helpText("Since \\(\\ w_{(1)}\\) has been defined to be a unit vector, it equivalently also satisfies")),
                                withMathJax(helpText("$$\\ w_{(1)}=\\arg\\max_{\\left||{w}\\right||=1}{\\{\\frac{w^TX^TXw}{w^Tw}}\\}$$")),
                                helpText("Further components can be defined by following formula"),
                                withMathJax(helpText("$$\\ \\widehat{X}_k=X-\\sum_{\\delta=1}^{k-1}Xw_{{(\\delta)}}w_{{(\\delta)}}^T$$"))
                              ),
                              # Show output
                              mainPanel(
                                h3(textOutput('caption')),
                                tabsetPanel(
                                  tabPanel("Component Plot",plotOutput("componentplot",height = 280*2, width = 250*2)),
                                  tabPanel("Scree Plot",plotOutput("screeplot", height = "300px"))
                                )
                                
                              )
                            )
                   )
                   
))